<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2qbqj8x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2qbqj8x/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2qbqj8x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2qbqj8x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2qbqj8x\appProdProjectContainer([
    'container.build_hash' => '2qbqj8x',
    'container.build_id' => 'bab17512',
    'container.build_time' => 1670786184,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2qbqj8x');
